### ISSUE TITLE
pyang: error: no such option: --submodule-only

### ISSUE THREAD

**Issue by nk000959** [Melacon/ntsim#2]
'./auto-load-yangs.sh' returned a non-zero code:2

I get the error mentioned in the subject upon execution of './docker-build-x-ran-device.sh' or './docker-build-o-ran-device.sh'. It would be the same for any of the other scripts. 

Environment used:
- Fedora 31 workstation
- pyang 2.3.2

**Comment by alexandrustancu** [comment]
I have pushed the new pyang dependency.

Please update the dependencies with `git submodule update` and try again.

**Comment by nk000959** [comment]
Thanks for the quick fix. I could successfully make the image.
